"""Add ability to store market images

Revision ID: 2ee45348d0c0
Revises: 9e2fc565f44e
Create Date: 2025-11-14 04:36:50.121202

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ee45348d0c0"
down_revision: Union[str, None] = "9e2fc565f44e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "markets",
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("markets", "logo_url")
    # ### end Alembic commands ###
